{% set name = "microsoft-kiota-serialization-multipart" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_multipart-{{ version }}.tar.gz
  sha256: b1851409205668d83f5c7a35a8b6fca974b341985b4a92841e95aaec93b7ca0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - microsoft-kiota-abstractions

test:
  imports:
    - kiota_serialization_multipart
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/multipart
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE

extra:
  anaconda-services:

    ref: https://anaconda.zendesk.com/agent/tickets/58810
    reason: Dependency for msgraph-sdk
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - xylar

