{% set name = "microsoft-kiota-serialization-multipart" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_multipart-{{ version }}.tar.gz
  sha256: 14e89e92582e6630ddbc70ac67b70bf189dacbfc41a96d3e1d10339e86c8dde5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
  run:
    - python
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0

test:
  imports:
    - kiota_serialization_multipart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-serialization-multipart-python
  summary: Implementation of Kiota Serialization Interfaces for Multipart serialization
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-serialization-multipart-python
  doc_url: https://github.com/microsoft/kiota-serialization-multipart-python/blob/main/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/48409
    reason: Dependenccy for msgraph-sdk
    recipe-maintainers:
      - ianaobi
